name: ptgest
services:
  database:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-db
    environment:
      - POSTGRES_USER=ptgest
      - POSTGRES_PASSWORD=ptgest
      - POSTGRES_DB=ptgest-db
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "5432:5432"